[package]
name = "ssd-web"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
dioxus = "0.4.3"
dioxus-web = "0.4.3"
ssd = { version = "0.23.0", path = "../crates/ssd", default-features = false, features = ["_web"] }
web-sys = "0.3.66"
