[package]
name = "ssd-web"
version = "0.22.0"
edition = "2024"
publish = false

[dependencies]
dioxus = "0.4.3"
dioxus-web = "0.4.3"
ssd = { version = "0.22.0", path = "../crates/ssd", default-features = false, features = ["_web"] }
web-sys = "0.3.66"